/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        int[] trueArr = {1, 2, 1, 4};
        int[] falseArr = {1, 2, 3, 4};
        int[] avgArr = {10, 3, 3, 4};
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] arrExpected = {55, 54, 60, 53, 59, 57, 61};

        assertTrue(classUnderTest.containsDuplicates(trueArr), "containsDuplicates should return 'true'");
        assertFalse(classUnderTest.containsDuplicates(falseArr), "containsDuplicates should return 'false'");
        assertEquals(6, classUnderTest.roll(6).length, "roll should return array of length 6");
        assertEquals(5, classUnderTest.average(avgArr), "average should return array average equal to 5");
        assertArrayEquals(arrExpected, classUnderTest.lowestAvg(weeklyMonthTemperatures), "lowestAvg should return the lowest array in the parent array which is {55, 54, 60, 53, 59, 57, 61}");


    }
}
