/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {
    public static void main(String[] args) {
        int[] resultArr = roll(4);

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        System.out.println(Arrays.toString(resultArr));
        System.out.println(containsDuplicates(resultArr));
        System.out.println(average(resultArr));
        System.out.println(Arrays.toString(lowestAvg(weeklyMonthTemperatures)));

    }

    public static int[] roll(int num) {
        Random random = new Random();
        int[] arr = new int[num];
        for (int i = 0; i < num; i++) {
            int rand = random.nextInt(6 - 1 + 1) + 1;
            arr[i] = rand;

        }
        return arr;
    }

    public static boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }

            }
        }
        return false;
    }
    public static float average(int[] arr){
        int arrLength = arr.length;
        int sum = 0;
        for (int i = 0; i < arr.length; i++) {
            sum = sum + arr[i];
        }

        return (float) sum/arrLength;
    }

    public static int[] lowestAvg(int[][] arr){
        float[] arrOfAvg = new float[arr.length];

        for (int i = 0; i < arr.length; i++) {
            int oneSum = 0;
            int oneArrLength = arr[i].length;
            for (int j = 0; j < oneArrLength; j++) {
                oneSum = oneSum + arr[i][j];

            }
            arrOfAvg[i] = (float) oneSum/oneArrLength;
        }
        float compare = arrOfAvg[0];
        for (int i = 0; i < arrOfAvg.length; i++){
            if (compare >= arrOfAvg[i]){
                compare = arrOfAvg[i];
            }
        }
        int arrIndex = 0;
        for (int i = 0; i < arrOfAvg.length; i++){
            if (compare == arrOfAvg[i]){
                arrIndex = i;
            }
        }


        return arr[arrIndex];
    }
}